
development:
  user_identifier: email_address
  default_plugin: 'buildit'

production:
  user_identifier: email_address
  default_plugin: 'buildit'

production:
  user_identifier: email_address
  default_plugin: 'buildit'

