
production:
  solr:
    hostname: localhost
    port: 8986
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8985
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    
test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING

    